import { constants } from 'http2';

type StatusCodeProps =
  | 'OK'
  | 'CREATED'
  | 'BAD_REQUEST'
  | 'NOT_FOUND'
  | 'UNAUTHORIZED'
  | 'FORBIDDEN'
  | 'TOO_MANY_REQUEST'
  | 'SERVER_ERROR'
  | 'BAD_GATEWAY'
  | 'METHOD_NOT_ALLOWED'
  | 'UNPROCESSABLE_CONTENT';

export const STATUS_CODE: Record<StatusCodeProps, number> = {
  OK: constants.HTTP_STATUS_OK,
  CREATED: constants.HTTP_STATUS_CREATED,
  BAD_REQUEST: constants.HTTP_STATUS_BAD_REQUEST,
  NOT_FOUND: constants.HTTP_STATUS_NOT_FOUND,
  UNAUTHORIZED: constants.HTTP_STATUS_UNAUTHORIZED,
  FORBIDDEN: constants.HTTP_STATUS_FORBIDDEN,
  TOO_MANY_REQUEST: constants.HTTP_STATUS_TOO_MANY_REQUESTS,
  SERVER_ERROR: constants.HTTP_STATUS_INTERNAL_SERVER_ERROR,
  BAD_GATEWAY: constants.HTTP_STATUS_BAD_GATEWAY,
  METHOD_NOT_ALLOWED: constants.HTTP_STATUS_METHOD_NOT_ALLOWED,
  UNPROCESSABLE_CONTENT: constants.HTTP_STATUS_UNPROCESSABLE_ENTITY,
};
